name: Release

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Run semantic-release
      - name: Release
        env:
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # this is the correct way worked for mongo project and ryshrash
        run: npx semantic-release
