name: Release

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      # Checkout the repository with full history
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Run semantic-release
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # Push updated changelog/package.json back to repo
      - name: Push changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(release): update changelog [skip ci]"
          file_pattern: "CHANGELOG.md package.json"
          branch: main
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"


# -------------------------------------------------------------------
# old working setup
# name: Release

# on:
#   push:
#     branches:
#       - main
#       - 'release/**'

# jobs:
#   release:
#     name: Semantic Release
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#       issues: write
#       pull-requests: write
#     steps:
#       # Checkout the repository with full history
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0 # Fetches all history for all branches and tags

#       # Setup Node.js
#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 22
#           cache: 'npm'

#       # Install dependencies
#       - name: Install Dependencies
#         run: npm ci

#       # Run semantic-release
#       - name: Release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: npx semantic-release
